const Map<String, dynamic> dummydata = {
  "message": "ファイルを受け取りました",
  "data": {
    'lmeData': {
      2: 'どちらでもない',
      3: '学習意欲が低い',
      6: 'どちらでもない',
      7: '学習意欲が低い',
      8: '学習意欲が低い',
      10: 'どちらでもない',
      12: 'どちらでもない',
      13: '学習意欲が低い',
      15: '学習意欲が低い',
      16: '学習意欲が高い',
      18: '学習意欲が高い',
      20: 'どちらでもない',
      21: '学習意欲が高い',
      22: 'どちらでもない',
      23: '学習意欲が高い',
      24: '学習意欲が低い',
      25: 'どちらでもない',
      26: '学習意欲が低い',
      28: '学習意欲が高い',
      29: '学習意欲が低い',
      31: 'どちらでもない',
      32: '学習意欲が高い',
      34: 'どちらでもない',
      36: 'どちらでもない',
      37: 'どちらでもない',
      39: '学習意欲が高い',
      43: 'どちらでもない',
      44: '学習意欲が高い',
      47: 'どちらでもない',
      49: '学習意欲が低い',
      50: '学習意欲が高い',
      51: '学習意欲が高い',
      52: 'どちらでもない',
      54: 'どちらでもない',
      55: '学習意欲が高い',
      56: '学習意欲が低い',
      58: 'どちらでもない',
      59: 'どちらでもない',
      60: 'どちらでもない',
      61: '学習意欲が高い',
      62: '学習意欲が低い',
      63: 'どちらでもない',
      64: 'どちらでもない',
      65: 'どちらでもない',
      66: 'どちらでもない',
      67: '学習意欲が低い',
      68: '学習意欲が高い',
      69: '学習意欲が高い',
      70: '学習意欲が低い',
      72: 'どちらでもない',
      73: 'どちらでもない',
      74: '学習意欲が高い',
      75: '学習意欲が高い',
      76: '学習意欲が高い',
      77: '学習意欲が高い',
      78: 'どちらでもない',
      79: 'どちらでもない',
      80: 'どちらでもない',
      81: '学習意欲が高い',
      82: '学習意欲が高い',
      83: '学習意欲が低い'
    },
    "number_col": [2, 8, 15, 16, 19, 20, 25, 29, 30, 36],
    'stID_col': 8
  }
};

const adjustData = [
  {"type": "Email", "index": 0, "value": 120},
  {"type": "Email", "index": 1, "value": 132},
  {"type": "Email", "index": 2, "value": 101},
  {"type": "Email", "index": 3, "value": 134},
  {"type": "Email", "index": 4, "value": 90},
  {"type": "Email", "index": 5, "value": 230},
  {"type": "Email", "index": 6, "value": 210},
  {"type": "Affiliate", "index": 0, "value": 220},
  {"type": "Affiliate", "index": 1, "value": 182},
  {"type": "Affiliate", "index": 2, "value": 191},
  {"type": "Affiliate", "index": 3, "value": 234},
  {"type": "Affiliate", "index": 4, "value": 290},
  {"type": "Affiliate", "index": 5, "value": 330},
  {"type": "Affiliate", "index": 6, "value": 310},
  {"type": "Video", "index": 0, "value": 0},
  {"type": "Video", "index": 1, "value": 232},
  {"type": "Video", "index": 2, "value": 201},
  {"type": "Video", "index": 3, "value": 154},
  {"type": "Video", "index": 4, "value": 190},
  {"type": "Video", "index": 5, "value": 330},
  {"type": "Video", "index": 6, "value": 410},
  {"type": "Direct", "index": 0, "value": 320},
  {"type": "Direct", "index": 1, "value": 332},
  {"type": "Direct", "index": 2, "value": 301},
  {"type": "Direct", "index": 3, "value": 334},
  {"type": "Direct", "index": 4, "value": 390},
  {"type": "Direct", "index": 5, "value": 330},
  {"type": "Direct", "index": 6, "value": 320},
  {"type": "Search", "index": 0, "value": 320},
  {"type": "Search", "index": 1, "value": 432},
  {"type": "Search", "index": 2, "value": 401},
  {"type": "Search", "index": 3, "value": 434},
  {"type": "Search", "index": 4, "value": 390},
  {"type": "Search", "index": 5, "value": 430},
  {"type": "Search", "index": 6, "value": 420},
];
