version: "3"

services:
  # db:
  #   container_name: "db"
  #   build: ./db
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=fruitdb

  #     # *** テスト用に全ホストからアクセス許可 ***
  #     - POSTGRES_HOST_AUTH_METHOD=trust 
  #     # ************************************

  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d # ファイルをマウントしてDBを立ち上げた後でSQLを自動実行
  #   networks:
  #     - app-net # ネットワークを指定して、コンテナ間で通信する

  server:
    # depends_on:
    #     - db # db起動後に立ち上げる
    # links:
    #     - db:db
    container_name: "server"
    build:
      context: ./server/
      dockerfile: Dockerfile
    # tty: true
    ports:
      - 8000:8000
    volumes:
      - ./server/app:/server/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - my_network
  
  frontend:
    container_name: "client"
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

